version: "3"

services:
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    privileged: true
    depends_on:
      - cadvisor
    volumes:
      - $(pwd)/prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    privileged: true
    environment:
      - GF_SECURITY_ADMIN_USER=${USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD}
    depends_on:
      - prometheus
        #    volumes:
      #      - $(pwd)/grafana/data:/var/lib/grafana
  node-exporter:
    image: prom/node-exporter:v1.9.0
    container_name: node-exporter
    ports:
      - 9100:9100
    command:
      - "--path.rootfs=/host"
    pid: "host"
    network_mode: "host"
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/host:ro,rslave
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8090:8080
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
