version: '3.9'

services:
  elasticsearch:
    image: elasticsearch:8.17.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.ml.use_auto_machine_memory_percent: true
      xpack.security.enrollment.enabled: true
    deploy:
      resources:
        limits:
          memory: "6G"
  kibana:
    container_name: kibana
    image: kibana:8.17.1
    ports:
      - "5601:5601"
#    environment:
#      ELASTICSEARCH_HOSTS: "https://elasticsearch:9200"
#    entrypoint: [ "/bin/bash", "-c", "/shared/entrypoint.sh" ]
#    volumes:
#      - kibana-volume:/shared
#
#volumes:
#  kibana-volume:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: LOCALDIR